### ISSUE TITLE
Tag links are hard-coded to webmaker.org

### ISSUE THREAD

**Issue by toolness** [mozilla/MakeAPI-Gallery#4]
Right now there is a `profileBaseURL` option in the `MakeGallery` constructor that allows profile links to point to places other than webmaker.org, which is useful when an app is pointing at staging rather than production.

However, there is no analogous mechanism for links to tag searches on webmaker.org. I added one in a local copy of one of my projects [here](https://github.com/toolness/weblitmapper/commit/21870f2ef9ce3d484291280a11c4e5152cb35ef7) which adds an analogous `tagBaseURL` option to the constructor.

However, this almost certainly requires clients to pass in both `tagBaseURL` and `profileBaseURL` options to the constructor. A better option might be to have a single `webmakerBaseURL` option that rebases all URLs which would normally begin with `https://webmaker.org/`. This would mean hardcoding the `/u/` and `/t/` paths, but I'm not sure what the use case for changing those is.

**Comment by cadecairos** [comment]
I'm not sure we should hardcode the `/u/` and `/t/` path, it's unlikely that some, if any, other sites would have that behaviour.

**Comment by toolness** [comment]
Oh, so I guess we're assuming that this can be used with sites that use the MakeAPI but that aren't linking back to Webmaker.org or one of its staging/dev environments? I wasn't sure what the use cases were...

**Comment by cadecairos** [comment]
Yes, I think we want to leave the possibility open for apps that use the Make API but don't necessarily want to use tag search/profiles on webmaker.org

**Comment by toolness** [comment]
Gotcha, that totally makes sense then!

----- Original Message -----
